### ISSUE TITLE
Possibly incompability

### ISSUE THREAD

**Issue by KamiSami** [MoriyaShiine/hourai-elixir#1]
Unsure if this can be fixed on your side, if it can it would be awesome to see quick fix for this, as for now i am 100% unable to log in to my server due to error.. I am going to paste the piece of log in here that it told me before the disconnect that says internal server error. It's not very big i think. It sounds like it might be incompatible with mkultra, not sure, i don't understand the log myself very well other than what it seems to sometimes complain about of some mods. Hopefully this piece of the log is correct and can help. Also to mention, this is "hourai-elixir-1.0.2" and forge "forge-14.23.5.2847" on Minecraft 1.12.2.

net.minecraft.util.ReportedException: Ticking player
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:459) ~[oq.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) ~[pa.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) ~[NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) ~[gw.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
Caused by: java.lang.NoSuchMethodError: net.minecraft.potion.Potion.func_188408_i()Z
	at moriyashiine.houraielixir.HouraiCapability$Handler.potionApplicable(HouraiCapability.java:125) ~[HouraiCapability$Handler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1107_Handler_potionApplicable_PotionApplicableEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70687_e(EntityLivingBase.java:764) ~[vp.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70690_d(EntityLivingBase.java:743) ~[vp.class:?]
	at com.chaosbuffalo.mkultra.core.PlayerPassiveAbility.applyEffect(PlayerPassiveAbility.java:55) ~[PlayerPassiveAbility.class:?]
	at com.chaosbuffalo.mkultra.core.PlayerPassiveAbility.execute(PlayerPassiveAbility.java:65) ~[PlayerPassiveAbility.class:?]
	at com.chaosbuffalo.mkultra.core.PlayerClassInfo.applyPassives(PlayerClassInfo.java:128) ~[PlayerClassInfo.class:?]
	at com.chaosbuffalo.mkultra.core.PlayerData.refreshPassiveTalents(PlayerData.java:458) ~[PlayerData.class:?]
	at com.chaosbuffalo.mkultra.core.PlayerData.onTick(PlayerData.java:1151) ~[PlayerData.class:?]
	at com.chaosbuffalo.mkultra.event.EntityEventHandler.onLivingUpdateTick(EntityEventHandler.java:202) ~[EntityEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_532_EntityEventHandler_onLivingUpdateTick_LivingUpdateEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:581) ~[ForgeHooks.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2095) ~[vp.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234) ~[aed.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382) ~[oq.class:?]
	... 9 more
[04:11:12] [Server thread/INFO] [net.minecraft.network.NetHandlerPlayServer]: The_Holiness lost connection: Internal server error

**Comment by MoriyaShiine** [comment]
That's... Very odd. It can't find a method from the vanilla potion class. Does mkultra modify potions in some way?

**Comment by KamiSami** [comment]
Also to add, it seems same thing happens when i drink potion of luck, i think luck is vanilla minecraft feature which i find odd for it to throw me out from of. And... It has custom potion effects i believe but it doesn't modify existing ones i think..

**Comment by KamiSami** [comment]
Just now relogged again and tried another pot and got DCd again after drinking fire resistance potion, want me to post the last piece of the log again?

**Comment by MoriyaShiine** [comment]
Yes please. This doesn't appear to happen using just this mod, maybe try posting an issue on their github?

**Comment by KamiSami** [comment]
There are now couple other mods mentioned too in the last one after i drank another potion of fire resistance. Here.

[Server thread/ERROR] [FML]: Index: 3 Listeners:
[04:40:22] [Server thread/ERROR] [FML]: 0: NORMAL
[04:40:22] [Server thread/ERROR] [FML]: 1: ASM: class electroblob.wizardry.item.ItemArtefact onPotionApplicableEvent(Lnet/minecraftforge/event/entity/living/PotionEvent$PotionApplicableEvent;)V
[04:40:22] [Server thread/ERROR] [FML]: 2: ASM: class cursedflames.bountifulbaubles.event.EventHandler potionApply(Lnet/minecraftforge/event/entity/living/PotionEvent$PotionApplicableEvent;)V
[04:40:22] [Server thread/ERROR] [FML]: 3: ASM: moriyashiine.houraielixir.HouraiCapability$Handler@775828c0 potionApplicable(Lnet/minecraftforge/event/entity/living/PotionEvent$PotionApplicableEvent;)V
[04:40:22] [Server thread/WARN] [net.minecraft.network.NetworkSystem]: Failed to handle packet for /127.0.0.1:64395
net.minecraft.util.ReportedException: Ticking player
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:459) ~[oq.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) ~[pa.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) ~[NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) ~[gw.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
Caused by: java.lang.NoSuchMethodError: net.minecraft.potion.Potion.func_188408_i()Z
	at moriyashiine.houraielixir.HouraiCapability$Handler.potionApplicable(HouraiCapability.java:125) ~[HouraiCapability$Handler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_915_Handler_potionApplicable_PotionApplicableEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70687_e(EntityLivingBase.java:764) ~[vp.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70690_d(EntityLivingBase.java:743) ~[vp.class:?]
	at net.minecraft.item.ItemPotion.func_77654_b(SourceFile:53) ~[ajd.class:?]
	at net.minecraft.item.ItemStack.func_77950_b(ItemStack.java:222) ~[aip.class:?]
	at net.minecraft.entity.EntityLivingBase.func_71036_o(EntityLivingBase.java:2789) ~[vp.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_71036_o(EntityPlayerMP.java:1125) ~[oq.class:?]
	at net.minecraft.entity.EntityLivingBase.func_184608_ct(EntityLivingBase.java:2688) ~[vp.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2097) ~[vp.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234) ~[aed.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382) ~[oq.class:?]
	... 9 more
[04:40:22]

**Comment by MoriyaShiine** [comment]
Found the issue, I was using a client-side only method. Will be fixed once curseforge approves the file. Will probably only take a few minutes.

**Comment by KamiSami** [comment]
Alright awesome, thanks.

**Comment by MoriyaShiine** [comment]
It's up, this happened because I down ported my 1.15 code and apparently one of the methods I used there was tagged a clientside in 1.12 haha.
